# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to GCP

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GCP_BUCKET: ${{ secrets.GCP_BUCKET }}

    steps:
      - uses: actions/checkout@v3
      # install dependencies
      - name: Install dependencies
        run: yarn
      # build app
      - name: build
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build

      - uses: actions/checkout@v3
      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Deploy
        run: gsutil -m rsync -d -c -r build/ gs://$GCP_BUCKET
