name: Deploy to GCP

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GCP_BUCKET: ${{ secrets.GCP_BUCKET }}

    steps:
      - uses: actions/checkout@v3
      # install dependencies
      - name: Install dependencies
        run: yarn
      # build app
      - name: build
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build/latest

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: build/latest

      - name: Upload to GCP bucket
        run: gsutil -m rsync -d -c -r build/latest gs://$GCP_BUCKET/build

      - name: Sync to GCP working directory
        run: gsutil rsync -r gs://$GCP_BUCKET ./react-ci-cd

      - name: Deploy
        run: cd react-ci-cd && gcloud app deploy
